admin_panel/urls.py
from django.contrib import admin
from django.urls import path
from .views import main_page, delete, edit, update, login, logout, create, category, create_category, delete_category, update_category
from .views import users, create_user, delete_user

app_name = "admin_panel"

urlpatterns = [
    path('', main_page, name="main_page"),
    path('delete/<int:id>/', delete, name="delete"),
    path('edit/<int:id>/', edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('login', login, name="login"),
    path('logout', logout, name="logout"),
    path('create', create, name="create"),


    path('category', category, name="category"),
    path('create_category', create_category, name="create_category"),
    path('delete_category/<int:id>', delete_category, name="delete_category"),
    path('update_category/<int:id>', update_category, name="update_category"),
    path('users', users, name="users"),
    path('create_user', create_user, name="create_user"),
    path('delete_user/<int:id>', delete_user, name="delete_user"),
]

news/urls.py
from django.contrib import admin
from django.urls import path, include
from news.views import main_page, post

app_name = "news"

urlpatterns = [
    path('', main_page, name='main_page'),
    path('post/<int:id>/', post, name='post'),
]

news_portal/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.shortcuts import HttpResponseRedirect

from django.conf.urls.static import static 
from django.conf import settings 

def redirect(request):
    return HttpResponseRedirect(reverse_lazy('news:main_page'))

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', redirect),
    path('news/', include('news.urls')),
    path('admin_panel/', include('admin_panel.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin_panel/models.py
from django.db import models

# Create your models here.

class Users(models.Model):
    name = models.CharField(max_length=100)
    user = models.CharField(max_length=100)
    password = models.CharField(max_length=250)
    role = models.IntegerField()

    def __str__(self):
        return self.name
    
    class Meta:
        db_table = 'Users'
        ordering = ['id']

admin_panel/views.py
from django.shortcuts import render, HttpResponseRedirect
from news.models import Post, Category
from django.urls import reverse_lazy
from .models import Users

# Create your views here.


# login and logout pages
# controling with sesssions

for_login_page = {
    'title': "LOGIN"
}

def login(request):
    if request.method == "POST":
        Puser = request.POST.get('user')
        password = request.POST.get('password')
        # users = Users.objects.all()
        # print('user: ', Puser)
        # print('password: ', password)
        # print(len(users))
        for user in Users.objects.all():
            print(user.user)
            print(user.password)
            if Puser == user.user and password == user.password:
                request.session['admin_id'] = user.id
                request.session['admin'] = user.name
                request.session['role'] = user.role
                request.session['same'] = False
                return HttpResponseRedirect(reverse_lazy('admin_panel:main_page'))
        else:
            for_login_page['wrong'] = "wrong"
            return render(request, "admin_panel/login.html", for_login_page)
    for_login_page['wrong'] = False
    return render(request, "admin_panel/login.html", for_login_page)

def logout(request):
    request.session['admin'] = False
    return HttpResponseRedirect(reverse_lazy('admin_panel:login'))





# post pages view or controller

for_main_page = {
    'title': "Post",
}

def main_page(request):
    if request.session['admin']:
        for_main_page['user'] = request.session['admin']
        for_main_page['role'] = request.session['role']
        for_main_page['posts'] = Post.objects.all()
        return render(request, 'admin_panel/post.html', for_main_page)
    else:
        return HttpResponseRedirect(reverse_lazy('admin_panel:login'))


def delete(request, id):
    if not request.session['admin']:
        return HttpResponseRedirect(reverse_lazy('admin_panel:login'))
    else:
        if request.session['admin']:
            post = Post.objects.get(id=id)
            category = Category.objects.get(id=post.category.id)
            category.category_post -= 1
            category.save()
            post.delete()
        return HttpResponseRedirect(reverse_lazy('admin_panel:main_page'))


def edit(request, id):
    if not request.session['admin']:
        return HttpResponseRedirect(reverse_lazy('admin_panel:login'))
    else:
        post = Post.objects.get(id=id)
        category = Category.objects.all()
        return render(request, 'admin_panel/edit.html', {'post': post, 'categorys': category, "title": "EDIT", 'user': request.session['admin']})


def update(request, id):
    if not request.session['admin']:
        return HttpResponseRedirect(reverse_lazy('admin_panel:login'))
    else:
        post = Post.objects.get(id=id)

        category = Category.objects.get(id=post.category.id)
        category.category_post -= 1
        category.save()

        category = Category.objects.get(id=int(request.POST.get('category')))
        category.category_post += 1
        category.save()

        post.title = request.POST.get('title')
        post.description = request.POST.get('description')
        post.category = category
        if request.POST.get('img') != "":
            post.img = request.FILES['img']
        post.save()

        return HttpResponseRedirect(reverse_lazy('admin_panel:main_page'))


for_create_page = {
    'title': "Create",
}

def create(request):
    if not request.session['admin']:
        return HttpResponseRedirect(reverse_lazy('admin_panel:login'))
    else:
        for_create_page['user'] = request.session['admin']
        for_create_page['role'] = request.session['role']
        for_create_page['categorys'] = Category.objects.all()
        if request.method == 'POST' and request.FILES['img']:
            title = request.POST.get('title')
            description = request.POST.get('description').strip()
            category = int(request.POST.get('category'))
            img = request.FILES['img']
            author = Users.objects.get(id=request.session['admin_id'])


            category_inc = Category.objects.get(id=category)
            category_inc.category_post += 1
            category_inc.save()
            news = Post.objects.create(title=title, description=description, category=Category.objects.get(id=category), img=img, author=author)
            news.save()
            return HttpResponseRedirect(reverse_lazy('admin_panel:main_page'))
        
        return render(request, "admin_panel/create.html", for_create_page)




# Category pages view and controller 

for_category_page = {
    'title': "Category",
}
def category(request):
    if not request.session['admin']:
        return HttpResponseRedirect(reverse_lazy('admin_panel:login'))
    else:
        for_category_page['user'] = request.session['admin']
        for_category_page['role'] = request.session['role']
        for_category_page['categorys'] = Category.objects.all()
        return render(request, "admin_panel/category.html", for_category_page)



def create_category(request):
    if not request.session['admin']:
        return HttpResponseRedirect(reverse_lazy('admin_panel:login'))
    else:
        if request.method == 'POST':
            name = request.POST.get('category')
            category = Category.objects.create(category_name=name, category_post=0)
            category.save()
            return HttpResponseRedirect(reverse_lazy('admin_panel:category'))
        return render(request, "admin_panel/create_category.html", {'title': 'Create Category', "user": request.session['admin'], 'role': request.session['role']})

def delete_category(request, id):
    if not request.session['admin']:
        return HttpResponseRedirect(reverse_lazy('admin_panel:login'))
    else:
        category = Category.objects.get(id=id)
        category.delete()

        return HttpResponseRedirect(reverse_lazy('admin_panel:category'))


def update_category(request, id):
    category = Category.objects.get(id=id)
    if request.method != 'POST':
        return render(request, 'admin_panel/update_category.html', {'category': category})
    
    category_name = request.POST.get('category')
    category.category_name = category_name
    category.save()
    return HttpResponseRedirect(reverse_lazy('admin_panel:category'))



# User pages View file and controller

def users(request):
    if not request.session['admin']:
        return HttpResponseRedirect(reverse_lazy('admin_panel:login'))
    else:
        if request.session['role'] == 1:
            user_page = {
                'title': "Users",
                'user': request.session['admin'],
                'role': request.session['role'],
                'admin_id': request.session['admin_id'],
                'users': Users.objects.all()
            }
            return render(request, "admin_panel/users.html", user_page)
        else:
            return HttpResponseRedirect(reverse_lazy('admin_panel:main_page'))

def create_user(request):
    if not request.session['admin']:
        return HttpResponseRedirect(reverse_lazy('admin_panel:login'))
    else:
        if request.session['role'] == 1:
            if request.method == 'POST':
                name = request.POST.get('name').strip()
                user = request.POST.get('user').strip()
                password = request.POST.get('password')
                role = request.POST.get('role')

                if Users.objects.filter(user=user):
                    request.session['same'] = True
                    return HttpResponseRedirect(reverse_lazy('admin_panel:create_user'))

                users = Users.objects.create(name=name, user=user, password=password, role=role)
                users.save()
                return HttpResponseRedirect(reverse_lazy('admin_panel:users'))
            user_page = {
                'title': "Add User",
                'user': request.session['admin'],
                'role': request.session['role'],
                'same': False
            }
            if request.session['same']:
                user_page['same'] = True
                request.session['same'] = False
            return render(request, 'admin_panel/create_user.html', user_page)
        else:
            return HttpResponseRedirect(reverse_lazy('admin_panel:main_page'))

def delete_user(request, id):
    if not request.session['admin']:
        return HttpResponseRedirect(reverse_lazy('admin_panel:login'))
    else:
        if request.session['role'] == 1:
            user = Users.objects.get(id=id)
            user.delete()
            return HttpResponseRedirect(reverse_lazy('admin_panel:users'))
        else:
            return HttpResponseRedirect(reverse_lazy('admin_panel:main_page'))

templates/admin_panel/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/main.css" %}" rel="stylesheet">
    <link href="{% static "css/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet">
    <link href="{% static "css/font-awesome/css/font-awesome.css" %}" rel="stylesheet">
    <link rel="icon" href="{% static "icons/admin.png" %}">
    <title>Admin - {{title}}</title>
  </head>
  <body style="background-color: #f1f1f1;">
    <div class="header col-lg-4">
        <div class="header-content">
            <a href="{% url 'admin_panel:main_page' %}">
                <h1 class="text-light float-left"> <span class="text-dark">ADMIN</span> PANEL</h1>
            </a>
        </div>
    </div>
    <nav id="nav">
        <h4 id="logout">{{user}} <a href="{% url 'admin_panel:logout' %}" class="text-secondary">LOGOUT</a> </h4>
        <div class="container">
            <ul>
                <a href="{% url 'admin_panel:main_page' %}"><li class="post_page">post</li></a>
                <a href="{% url 'admin_panel:category' %}"><li class="category_page">category</li></a>
                {% if role %}
                    <a href="{% url 'admin_panel:users' %}"><li class="users_page">users</li></a>
                {% endif %}
            </ul>
        </div>
    </nav>

    
    
    {% block home %}{% endblock home %}
    {% block scriptblock %} {% endblock scriptblock %}
    <script src="{% static "js/bootstrap.bundle.min.js" %}"></script>
    <script src="{% static "js/imag_preview.js" %}"></script>
</body>
</html>

templates/admin_panel/category.html
{% extends 'admin_panel/base.html' %}
{% load static %}


{% block home %}
<style>
    .category_page{
        background-color: #6687B2;
    }
</style>  


<div class="container">
    <div class="admin_posts rounded mt-4 p-3" style="background-color: rgba(0,0,0,.5)!important;">
        <div class="col-12">
            <h1 class="text-light d-inline">All Categorys</h1>
            <button style="float: right!important;" class="btn mr-auto button"><a class="text-light" href="{% url 'admin_panel:create_category' %}"> Add Category </a></button>
        </div>
        <table class="table table-light table-striped text-center">
            <thead>
                <tr class="bg-dark text-light">
                    <th class="col-2 bg-dark">S.NO.</th>
                    <th class="col-4 bg-dark">CATEGORY NAME</th>
                    <th class="bg-dark">NO. OF POSTS</th>
                    <th class="col-1 bg-dark">EDIT</th>
                    <th class="col-1 bg-dark">DELETE</th>
                </tr>
            </thead>
            <tbody>
                
                {% for category in categorys %}
                    <tr>
                        <td>{{category.id}}</td>
                        <td>{{category.category_name}}</td>
                        <td>{{category.category_post}}</td>
                        <td><a href="{% url 'admin_panel:update_category' category.id %}"><i class="fa fa-edit text-warning"></i></a></td>
                        <td><a href="{% url 'admin_panel:delete_category' category.id %}"><i class="fa fa-trash text-danger"></i></a></td>
                    </tr>                  
                {% endfor %}

            </tbody>
        </table>
    </div>
</div>

{% endblock home %}

templates/admin_panel/create.html
{% extends 'admin_panel/base.html' %}
{% load static %}

{% block home %}
  <div class="container pt-5 col-6 bg-light py-4">
      <h1 class="text-center" style="color: #6687b2">New Post</h1>
    <form action="{% url 'admin_panel:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
          <label for="title" class="form-label">Enter Title</label>
          <input type="text" class="form-control" id="title" name="title" autocomplete="off" placeholder="News Title" required>
        </div>
        <div class="mb-3">
          <label for="description" class="form-label">Enter Description</label>
          <textarea name="description" id="description" cols="30" rows="10" class="form-control" placeholder="News Description" required></textarea>
        </div>
        <div class="mb-3">
            <label for="category" class="form-label">Category</label>
            <select name="category" id="category" class="form-control" required>
                {% comment %} <option selected disabled>Category</option> {% endcomment %}
                {% for category in categorys %}
                <option value="{{category.id}}">{{category.category_name}}</option>
                {% endfor %}
            </select>
        </div>
        <div class="mb-3">
            <!-- <label for="img" class="form-label btn btn-primary">Upload Image</label> -->
          <input type="file" id="img" name="img" class="form-control d-none" required>
          <label for="img" class="btn button col-6" style="border-radius: 4px 4px 0 0;">Upload Image</label>
          <img src="" class="img" id="image" width="50%">
        </div>
        <button type="submit" class="btn btn-primary mt-4">Create</button>
    </form>
</div>
{% endblock home %}

templates/admin_panel/create_category.html
{% extends 'admin_panel/base.html' %}
{% load static %}

{% block home %}
  
<div class="container pt-5 col-6 bg-light py-4">
    <h1 class="text-center" style="color: #6687b2">New Category</h1>
  <form action="{% url 'admin_panel:create_category' %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="mb-3">
        <label for="category" class="form-label">Cateogry Name</label>
        <input type="text" class="form-control" id="category" name="category" autocomplete="off" placeholder="News Category" required>
      </div>
      
      
      <button type="submit" class="btn btn-primary">Create</button>
  </form>
</div>

{% endblock home %}

templates/admin_panel/create_user.html
{% extends 'admin_panel/base.html' %}
{% load static %}

{% block home %}
  
<div class="container pt-5 col-6 bg-light py-4">
    <h1 class="text-center" style="color: #6687b2">Add User</h1>
  <form action="{% url 'admin_panel:create_user' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% if same %}
            <div class="alert alert-danger" role="alert">
                <strong>User Already taken user other</strong>
            </div>
        {% endif %}
      <div class="mb-3">
        <label for="name" class="form-label">Full Name</label>
        <input type="text" class="form-control" id="name" name="name" autocomplete="off" placeholder="Full Name" required>
      </div>
      
      <div class="mb-3">
        <label for="user" class="form-label">User</label>
        <input type="text" class="form-control" id="user" name="user" autocomplete="off" placeholder="User" required>
      </div>
      
      <div class="mb-3">
        <label for="password" class="form-label">Password</label>
        <input type="password" class="form-control" id="password" name="password" autocomplete="off" placeholder="password" required>
      </div>
      
      <div class="mb-3">
        <label for="role" class="form-label">Role</label>
        <select class="form-control" name="role" id="role">
            <option value="0">Normal User</option>
            <option value="1">Admin User</option>
        </select>
      </div>
      
      <button type="submit" class="btn btn-primary">Add</button>
  </form>
</div>

{% endblock home %}

templates/admin_panel/edit.html
{% extends 'admin_panel/base.html' %}
{% load static %}


{% block home %}
    
<div class="container pt-5 col-6 bg-light py-4">
    <h1 class="text-center text-dark">EDIT NEWS</h1>
  <form action="{% url 'admin_panel:update' post.id %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="mb-3">
        <label for="title" class="form-label">Title</label>
        <input type="text" class="form-control" id="title" name="title" value="{{post.title}}" autocomplete="off" placeholder="News Title" required>
      </div>
      <div class="mb-3">
        <label for="description" class="form-label">Description</label>
        <textarea name="description" id="description" cols="30" rows="10" class="form-control" placeholder="News Description" required>{{post.description}}</textarea>
      </div>
      <div class="mb-3">
          <label for="category" class="form-label">Category</label>
          <select name="category" id="category" class="form-control" required>
              {% comment %} <option selected disabled>Category</option> {% endcomment %}
              {% for category in categorys %}
              <option
                {% if category.id == post.category.id %}
                  selected
                {% endif %}
              value="{{category.id}}">{{category.category_name}}</option>
              {% endfor %}
          </select>
      </div>
      <div class="mb-3">
        <input type="file" id="img" name="img" class="form-control d-none">
      </div>
      <label for="img" class="btn button col-6" style="border-radius: 4px 4px 0 0;">Upload Image</label>
      <img src="{{post.img.url}}" width="50%" style="display: block" id="image">
      
      <button type="submit" class="btn btn-primary mt-3">Update</button>
  </form>
</div>

{% endblock home %}

templates/admin_panel/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet">
    <link href="{% static "css/font-awesome/css/font-awesome.css" %}" rel="stylesheet">
    <link rel="icon" href="{% static 'icons/logo.png' %}">
    <title>{{title}}</title>
</head>
<body>
    <div class="main_div">
        <div class="login col-xl-3 col-lg-4 col-md-6 col-8 p-4">
            <h1 class="text-center py-4">LOGIN <i class="fa fa-user-o"></i> </h1>

            <form action="{% url 'admin_panel:login' %}" method="POST">

                {% csrf_token %}


                <label for="user" class="user_label">Enter User</label>
                <input type="text" name="user" id="user" class="col-12" onfocus="Focus(this)" onblur="Blur(this)" autocomplete="off" required>
                <div class="inputcolor mb-3 first"></div>

                <label for="password" class="password_label">Enter Password</label>
                <input type="password" name="password" id="password" class="col-12" onfocus="Focus(this)" onblur="Blur(this)" autocomplete="off" required>
                <div class="inputcolor mb-5 second"></div>

                <button type="submit" class="btn button" id="button">Login</button>    
            </form>
            
            {% if wrong %}
            <div class="alert alert-danger alert-dismissible fade show text-center mt-5" role="alert">
                <strong>Wrong User and Password</strong>
            </div>
            {% endif %}


        </div>
    </div>

    <script>
        user = document.getElementById('user')
        password = document.getElementById('password')
        button = document.getElementById('button')

        user.addEventListener('keyup', buttonFunc)
        password.addEventListener('keyup', buttonFunc)


        button.disabled = "disabled"
        
        function buttonFunc(){
            if(user.value == "" || password.value == ""){
                button.disabled = "disabled"
            }else{
                button.disabled = ""
            }
        }

        function Focus(elem){
            elem.previousElementSibling.style.bottom = "0"
        }
        function Blur(elem){
            if(elem.value == ""){
                elem.previousElementSibling.style.bottom = "-20px"
            }
        }
    </script>
    <script src="{% static "js/bootstrap.bundle.min.js" %}"></script>
</body>
</html>

templates/admin_panel/post.html
{% extends "admin_panel/base.html" %}
{% load static %}

{% block home %}
<style>
    .post_page{
        background-color: #6687B2;
    }
</style>


<div class="container">
    <div class="admin_posts rounded mt-4 p-3" style="background-color: rgba(0,0,0,.5)!important;">
        <div class="col-12">
            <h1 class="text-light d-inline">All Posts</h1>
            <button style="float: right!important;" class="btn mr-auto button"><a class="text-light" href="{% url 'admin_panel:create' %}"> Add Post </a></button>
        </div>
        <table class="table table-light table-striped">
            <thead>
                <tr class="bg-dark text-light">
                    <!-- <th class="col-1">ID</th> -->
                    <th class="col-4 bg-dark text-center">TITLE</th>
                    <th class="bg-dark">CATEGORY</th>
                    <th class="bg-dark">DATE</th>
                    <th class="bg-dark">AUTHOR</th>
                    <th class="col-1 bg-dark">EDIT</th>
                    <th class="col-1 bg-dark">DELETE</th>
                </tr>
            </thead>
            <tbody>
                
                {% for post in posts %}
                    <tr>
                        <!-- <td>{{post.id}}</td> -->
                        <td>{{post.title}}</td>
                        <td>{{post.category.category_name}}</td>
                        <td>{{post.post_date}}</td>
                        <td>{{post.author.name}}</td>
                        <td><a href="{% url 'admin_panel:edit' post.id %}"><i class="fa fa-edit text-warning"></i></a></td>
                        <td><a href="{% url 'admin_panel:delete' post.id %}"><i class="fa fa-trash text-danger"></i></a></td>
                    </tr>                  
                {% endfor %}

            </tbody>
        </table>
    </div>
</div>

{% endblock home %}

templates/admin_panel/update_category.html
{% extends 'admin_panel/base.html' %}
{% load static %}

{% block home %}
  
<div class="container pt-5 col-6 bg-light py-4">
    <h1 class="text-center" style="color: #6687b2">New Category</h1>
  <form action="{% url 'admin_panel:update_category' category.id %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="mb-3">
        <label for="category" class="form-label">Cateogry Name</label>
        <input type="text" class="form-control" id="category" name="category" autocomplete="off" placeholder="News Category" value="{{category.category_name}}" required>
      </div>
      
      
      <button type="submit" class="btn btn-primary">Create</button>
  </form>
</div>

{% endblock home %}

templates/admin_panel/users.html
{% extends 'admin_panel/base.html' %}
{% load static %}


{% block home %}
<style>
    .users_page{
        background-color: #6687B6;
    }
</style>  


<div class="container">
    <div class="admin_posts rounded mt-4 p-3" style="background-color: rgba(0,0,0,.5)!important;">
        <div class="col-12">
            <h1 class="text-light d-inline">Users</h1>
            <button style="float: right!important;" class="btn mr-auto button">
                <a class="text-light" href="{% url 'admin_panel:create_user' %}">
                    Add User 
                </a>
            </button>
        </div>
        <table class="table table-light table-striped text-center">
            <thead>
                <tr class="bg-dark text-light">
                    <th class="col-2 bg-dark">S.NO.</th>
                    <th class="col-4 bg-dark">NAME</th>
                    <th class="bg-dark">USER</th>
                    <th class="bg-dark">ROLE</th>
                    <!-- <th class="col-1 bg-dark">EDIT</th> -->
                    <th class="col-1 bg-dark">DELETE</th>
                </tr>
            </thead>
            <tbody>
                
                {% for user in users %}
                <tr>
                    <td>{{user.id}}</td>
                    <td>{{user.name}}</td>
                    <td>{{user.user}}</td>
                    {% if user.role %}
                    <td> Admin </td>
                    {% else %}
                    <td> Normal </td>
                    {% endif %}
                    {% comment %} <td><a href="{% url 'admin_panel:update_user' user.id %}"><i class="fa fa-edit text-warning"></i></a></td> {% endcomment %}
                    {% if admin_id == user.id %}
                        <td class="text-primary">Active</td>
                    {% else %}
                        <td><a href="{% url 'admin_panel:delete_user' user.id %}"><i class="fa fa-trash text-danger"></i></a></td>
                    {% endif %}
                    </tr>                  
                {% endfor %}

            </tbody>
        </table>
    </div>
</div>

{% endblock home %}