news/urls.py
from django.contrib import admin
from django.urls import path, include
from news.views import main_page, post

app_name = "news"

urlpatterns = [
    path('', main_page, name='main_page'),
    path('post/<int:id>/', post, name='post'),
]

news_portal/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.shortcuts import HttpResponseRedirect

from django.conf.urls.static import static 
from django.conf import settings 

def redirect(request):
    return HttpResponseRedirect(reverse_lazy('news:main_page'))

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', redirect),
    path('news/', include('news.urls')),
    path('admin_panel/', include('admin_panel.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/models.py
from django.db import models
from admin_panel.models import Users

# Create your models here.
class Category(models.Model):
    category_name = models.CharField(max_length=30, unique=True)
    category_post = models.IntegerField()

    def __str__(self):
        return self.category_name + " - " + str(self.category_post)
    
    class Meta:
        db_table = 'Category'
        ordering = ['id']
  

class Post(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    category = models.ForeignKey(Category, blank=True, null=True, on_delete=models.CASCADE)
    post_date = models.DateTimeField(auto_now=False, auto_now_add=True)
    img = models.ImageField(upload_to="images", blank=True, null=True)
    author = models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.title + " - " + self.category.category_name

    class Meta:
        db_table = 'Post'
        ordering = ['-post_date']

news/views.py
from django.shortcuts import render, HttpResponseRedirect
from news.models import Category, Post
from django.urls import reverse_lazy
# Create your views here.

category = Category.objects.all()
post = Post.objects.all()

for_main_page = {
    'title': "news",
    "categorys": category,
    'posts': Post.objects.all(),
    'recent': Post.objects.all()[:3],
    'search': False
}

for_post_page = {
    'title': 'News Post',
    'home': 'active',
    'category': Category.objects.all()
}


def main_page(request):
    if request.GET.get('id'):
        for_main_page['posts'] = Post.objects.all().filter(category=request.GET.get('id'))
        for_main_page['active'] = Category.objects.get(id=request.GET.get('id')).category_name
        for_main_page['home'] = ''
    else:
        for_main_page['posts'] = Post.objects.all()
        for_main_page['home'] = 'active'
        for_main_page['active'] = ''

    return render(request, 'news/home.html', for_main_page)


def post(request, id):
    try:
        for_post_page['post'] = Post.objects.get(id=id)
        return render(request, 'news/post.html', for_post_page)
    except:
        return HttpResponseRedirect(reverse_lazy('news:main_page'))

for_new = {
    'categorys': Category.objects.all(),
}

templates/news/home.html
{% extends "news/index.html" %}
{% load static %}
{% block home %}


<div class="container pt-4">
    <div class="row">
        <div id="small_screen" class="col-lg-4 px-3 mt-lg-0 mt-sm-5 recent mb-5">
            <div class="bg-light rounded p-3">
                <div id="line"></div>
                <h1 id="for_line">SEARCH</h1>
                <div id="search" class="search">
                        <div class="col-12 row m-0 search2">
                            <div class="col-9 m-0 p-0 float-left">
                                <input id="search_char" type="text" class="small_input form-control" placeholder="search ...">
                            </div>
                            <div class="col-3 float-left m-0 p-0">
                                <button id="search_btn" type="button" class="small btn btn-danger col-12"><i class="fa fa-search" aria-hidden="true"></i></button>
                            </div>
                        </div>
                </div>
            </div>
            <br>
            <div class="bg-light rounded py-3 recent_box">
                <div class="p-3 pt-0">
                    <div id="line" class="ml-3"></div>
                    <h1 id="for_line">RECENT NEWS</h1>
                </div>
                <div style="display: flex;" class="recent_photos">
                    {% for post in recent %}
                        <div class="recent_items">
                            <a href="{% url 'news:post' post.id %}">
                                <div class="recent_img" style="background-image: url('{{post.img.url}}');">
                                    <div class="img_child">
                                        See More
                                    </div>
                                </div>
                            </a>
                            <h3 class="text-warning">{{post.title}}</h3>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        
        <div class="col-lg-8 col-md-12 px-3">
            <div class="bg-light rounded p-3">
                {% if active %}
                    <h2>{{active}} News</h2>
                    <hr>
                {% endif %}
                {% for post in posts %}
                {% if post %}
                  
                <div class="post" style="display: none">
                    <a href="{% url 'news:post' post.id %}">
                        {% if post.img %}
                        <div class="image" style='background-image: url(" {{post.img.url}} ");'></div> 
                        {% endif %}
                    </a>
                    <div class="post_content">
                        <h1 class="post_title">{{post.title}}</h1>
                        <p class="post_type">{{post.category.category_name}} | {{post.post_date}}</p>
                        <p class="post_detail"> 
                            <span class="description">
                                {{post.description}}
                            </span>
                            <a href="{% url 'news:post' post.id %}">
                                <button class="btn btn-sm">Read more</button>    
                            </a>
                        </p>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
                <h1 id="no_item"></h1>
            </div>
        </div>
        

        <div class="col-lg-4 px-3 mt-lg-0 mt-sm-5 recent">
            <div class="bg-light rounded p-3">
                <div id="line"></div>
                <h1 id="for_line">SEARCH</h1>
                <div id="search" class="search">
                    <!-- <form> -->
                        <div class="col-12 row m-0 search2">
                            <div class="col-9 m-0 p-0 float-left">
                                <input type="text" class="larg_input form-control" placeholder="search ...">
                            </div>
                            <div class="col-3 float-left m-0 p-0">
                                <button type="button" class="larg btn btn-danger col-12"><i class="fa fa-search" aria-hidden="true"></i></button>
                            </div>
                        </div>
                    <!-- </form> -->
                </div>
            </div>
            <br>
            <div class="bg-light rounded py-3 recent_box">
                <div class="p-3 pt-0">
                    <div id="line" class="ml-3"></div>
                    <h1 id="for_line">RECENT NEWS</h1>
                </div>
                <div style="display: flex;" class="recent_photos">
                    {% for post in recent %}
                        <div class="recent_items">
                            <a href="{% url 'news:post' post.id %}">
                                <div class="recent_img" style="background-image: url('{{post.img.url}}');">
                                    <div class="img_child">
                                        See More
                                    </div>
                                </div>
                            </a>
                            <h3 class="text-warning">{{post.title}}</h3>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

<div class="pagination">
    <ul id="pagination">
        <li style="width: 60px; border-radius: 4px 0 0 4px;" id='prev' onclick="prev()">Prev</li>
        <!-- <script>
            for(i=1;i<=total;i++){
                document.write(`
                <li class="page_item" onclick='pagination("${i}")')>${i}</li>
                `)
            }
        </script> -->
        <li style="width: 60px; border-radius: 0 4px 4px 0;" id='next' onclick="next()">Next</li>
    </ul>
</div>
{% endblock home %}

{% block scriptblock %}
<script>
    var new_description = null
    var new_title = null
    var post = document.querySelectorAll('.post')
    var title = document.querySelectorAll('.post_title')
    var description = document.querySelectorAll('.description')
    
    for(var j=0;j<description.length;j++){
        if(description[j].innerHTML.trim().length > 130){
            new_description = description[j].innerHTML.trim().slice(0,130)
            description[j].innerHTML = new_description + " ...."
        }
    }
    
    
    for(var j=0;j<title.length;j++){
        if(title[j].innerHTML.trim().length > 17){
            new_title = title[j].innerHTML.trim().slice(0,17)
            title[j].innerHTML = new_title + " ...."
        }
    }
    

    if(post.length==0){
        document.getElementById('no_item').innerHTML = "This Category Has no <span class='text-danger'>POST</span> right now"
    }
    
    
    var ID=1
    const limit = 3
    var total = Math.ceil( post.length / limit )    


    window.addEventListener('resize',resize)
    function resize(){
        if(window.innerWidth <= 991){
            document.querySelector('.larg').id = ''
            document.querySelector('.larg_input').id = ''

            document.querySelector('.small').id = 'search_btn'
            document.querySelector('.small_input').id = 'search_char'
        }else{
            document.querySelector('.small').id = ''
            document.querySelector('.small_input').id = ''
            
            document.querySelector('.larg').id = 'search_btn'
            document.querySelector('.larg_input').id = 'search_char'
        }

        var button = document.getElementById('search_btn')
        button.addEventListener('click',search)
        document.getElementById("search_char").addEventListener("keyup",search)
    }
    resize()
    


    var page = document.getElementById('pagination')

    
    for(i=1;i<=total;i++){
        var li = document.createElement('li')
        var li_nu = document.createTextNode(i)
        li.appendChild(li_nu)
        var loc = page.childNodes.length-2
        page.insertBefore(li,page.childNodes[loc])
        page.childNodes[loc].classList.add('page_item')
    }


    function pagination(id){
            ID = Number(id)
            var page_item = document.querySelectorAll('.page_item')
            for(var j=0;j<page_item.length;j++){
                page_item[j].classList.remove('active')
            }
            page_item[id-1].classList.add('active')
            
            
            for(let i=0;  i<post.length;  i++){
                post[i].style.display = "none"
            }
            for(let i=id*limit-limit;  i<id*limit;  i++){
                if(post[i]){
                    post[i].style.display = "block"
                }
            }

            if(ID==1){
                document.getElementById('prev').style.display = "none"
            }else{
                document.getElementById('prev').style.display = "inline-block"
            }
            
            if(ID==page_item.length){
                document.getElementById('next').style.display = "none"
            }else{
                document.getElementById('next').style.display = "inline-block"
            }
        }
        
        
        
        window.addEventListener('load', pagination(ID))
        
        
        
        function next(){
            ID=ID+1
            pagination(ID)
        }
        
        function prev(){
            ID=ID-1
            pagination(ID)
        }


        var page_item = document.querySelectorAll('.page_item')
        for(i=0;i<page_item.length;i++){
            var val = page_item[i].innerHTML
            page_item[i].setAttribute('onclick', `pagination(${val})`)
        }
</script>
{% endblock scriptblock %}

templates/news/index.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/main.css" %}" rel="stylesheet">
    <link href="{% static "css/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet">
    <link href="{% static "css/font-awesome/css/font-awesome.css" %}" rel="stylesheet">
    <link rel="icon" href="{% static "icons/news.png" %}">
    <title>{{title}}</title>
    <style>
        .{{active}}{
            background-color: #6687b2;
        }
    </style>
  </head>
  <body style="background-color: #f1f1f1;">
    <div class="header col-lg-4">
        <div class="header-content">
            <a href="{% url 'news:main_page' %}">
                <h1 class="text-light"> <span class="text-dark">N</span>EWS</h1>
            </a>
        </div>
    </div>
    <nav id="nav">
        <div class="container">
            <ul>
                <a href="/news"><li class="{{home}}">home</li></a>
                {% for category in categorys %}
                <a href="/news/?id={{category.id}}"><li class="{{category.category_name}}">{{category.category_name}}</li></a>
                {% endfor %}
            </ul>
        </div>
    </nav>

    {% block home %}{% endblock home %}
    {% block scriptblock %} {% endblock scriptblock %}


    <script src="{% static "js/bootstrap.bundle.min.js" %}"></script>
    <script src='{% static "js/search.js" %}'></script>
</body>
</html>

templates/news/new.html
{% extends "news/index.html" %}

{% block home %}
  <div class="container pt-5 col-6 bg-light py-4">
      <h1 class="text-center text-primary">Upload News</h1>
    <form action="{% url 'news:new' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
          <label for="title" class="form-label">Enter Title</label>
          <input type="text" class="form-control" id="title" name="title" autocomplete="off" placeholder="News Title" required>
        </div>
        <div class="mb-3">
          <label for="description" class="form-label">Enter Description</label>
          <textarea name="description" id="description" cols="30" rows="10" class="form-control" placeholder="News Description" required></textarea>
        </div>
        <div class="mb-3">
            <label for="category" class="form-label">Category</label>
            <select name="category" id="category" class="form-control" required>
                {% comment %} <option selected disabled>Category</option> {% endcomment %}
                {% for category in categorys %}
                <option value="{{category.id}}">{{category.category_name}}</option>
                {% endfor %}
            </select>
        </div>
        <div class="mb-3">
            <!-- <label for="img" class="form-label btn btn-primary">Upload Image</label> -->
          <input type="file" id="img" name="img" class="form-control" required>
        </div>
        
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>
{% endblock home %}

templates/news/post.html
{% extends "news/index.html" %}
{% block home %}
  
    <div id="post" class="col-8 m-auto bg-light mt-3 rounded p-3">
        <h2 class="mt-4" style="font-weight: bold; color: #6687b2;">{{post.title}}</h2>
        <h5>{{post.category.category_name}}  ||  {{post.post_date}}</h5>
        <div style="display: flex; justify-content: center;">
            <img src="{{post.img.url}}" class="col-lg-6 col-md-8 col-sm-10 col-12">
        </div>
        <p>{{post.description}}</p>
    </div>

{% endblock home %}


{% block scriptblock %}

{% endblock scriptblock %}